version: 0.2.1
baudrate: 1000000
port: /dev/ttyUSB4
max_current: 2000
type: right
control_mode: current_based_position
motor_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
joint_names:
- middle_mcp
- ring_mcp
- ring_pip
- ring_abd
- thumb_pip
- thumb_dip
- thumb_abd
- thumb_mcp
- index_pip
- index_mcp
- index_abd
- middle_abd
- middle_pip
- pinky_mcp
- pinky_pip
- pinky_abd
- wrist
joint_to_motor_map:
  thumb_mcp: -8
  thumb_abd: -7
  thumb_pip: -5
  thumb_dip: -6
  index_abd: -11
  index_mcp: -10
  index_pip: -9
  middle_abd: -12
  middle_mcp: -1
  middle_pip: -13
  ring_abd: -4
  ring_mcp: -2
  ring_pip: -3
  pinky_abd: -16
  pinky_mcp: -14
  pinky_pip: -15
  wrist: -17
joint_roms:
  thumb_mcp:
  - -0.836224
  - 0.836224
  thumb_abd:
  - -0.450333
  - 0.450333
  thumb_pip:
  - -1.178385
  - 1.178385
  thumb_dip:
  - -1.081721
  - 1.081721
  index_abd:
  - -0.566177
  - 0.566177
  index_mcp:
  - -1.057938
  - 1.057938
  index_pip:
  - -1.053335
  - 1.053335
  middle_abd:
  - -0.654403
  - 0.654403
  middle_mcp:
  - -1.090927
  - 1.090927
  middle_pip:
  - -0.92138
  - 0.92138
  ring_abd:
  - -0.622948
  - 0.622948
  ring_mcp:
  - -1.005003
  - 1.005003
  ring_pip:
  - -1.04106
  - 1.04106
  pinky_abd:
  - -0.75567
  - 0.75567
  pinky_mcp:
  - -1.084022
  - 1.084022
  pinky_pip:
  - -1.114709
  - 1.114709
  wrist:
  - -1.416977
  - 1.416977
neutral_position:
  1: 0.239359
  2: 0.641361
  3: 1.181454
  4: 0.102802
  5: 5.919543
  6: 1.270446
  7: 4.831685
  8: 5.301198
  9: -0.151901
  10: 7.065707
  11: 5.658703
  12: 6.315407
  13: 7.472311
  14: 0.090527
  15: 1.437691
  16: 5.391725
  17: 6.32001
calib_current: 85
calib_step_size: 0.1
calib_step_period: 0.002
calib_num_stable: 10
calib_threshold: 0.01
calib_sequence:
- step: 1
  joints:
    thumb_mcp: flex
- step: 2
  joints:
    thumb_mcp: extend
- step: 3
  joints:
    thumb_abd: flex
- step: 4
  joints:
    thumb_abd: extend
- step: 5
  joints:
    thumb_pip: flex
- step: 6
  joints:
    thumb_pip: extend
- step: 7
  joints:
    thumb_dip: flex
- step: 8
  joints:
    thumb_dip: extend
- step: 9
  joints:
    index_abd: flex
    middle_abd: flex
    ring_abd: flex
    pinky_abd: flex
- step: 10
  joints:
    index_abd: extend
    middle_abd: extend
    ring_abd: extend
    pinky_abd: extend
- step: 11
  joints:
    index_mcp: flex
- step: 12
  joints:
    index_mcp: extend
- step: 13
  joints:
    index_pip: flex
- step: 14
  joints:
    index_pip: extend
- step: 15
  joints:
    middle_mcp: flex
- step: 16
  joints:
    middle_mcp: extend
- step: 17
  joints:
    middle_pip: flex
- step: 18
  joints:
    middle_pip: extend
- step: 19
  joints:
    ring_mcp: flex
- step: 20
  joints:
    ring_mcp: extend
- step: 21
  joints:
    ring_pip: flex
- step: 22
  joints:
    ring_pip: extend
- step: 23
  joints:
    pinky_mcp: flex
- step: 24
  joints:
    pinky_mcp: extend
- step: 25
  joints:
    pinky_pip: flex
- step: 26
  joints:
    pinky_pip: extend
- step: 27
  joints:
    wrist: flex
- step: 28
  joints:
    wrist: extend
joint_offsets:
  thumb_mcp: 4.626081
  thumb_abd: 4.752666
  thumb_pip: 5.825947
  thumb_dip: 1.150767
  index_abd: 5.451565
  index_mcp: 6.276281
  index_pip: -0.490227
  middle_abd: 6.333052
  middle_mcp: 6.860103
  middle_pip: -0.206371
  ring_abd: 0.001534
  ring_mcp: 0.064443
  ring_pip: 0.550066
  pinky_abd: 5.555134
  pinky_mcp: -0.580754
  pinky_pip: 0.883022
  wrist: 6.245594
motor_range:
  1:
  - -1.127751
  - 0.71501
  2:
  - -0.94056
  - 1.069446
  3:
  - -0.490994
  - 1.591127
  4:
  - -0.621414
  - 0.624483
  5:
  - 4.647562
  - 7.004332
  6:
  - 0.069046
  - 2.232487
  7:
  - 4.302333
  - 5.202999
  8:
  - 3.789858
  - 5.462305
  9:
  - -1.543562
  - 0.563108
  10:
  - 5.218343
  - 7.334219
  11:
  - 4.885388
  - 6.017742
  12:
  - 5.678649
  - 6.987454
  13:
  - 5.769176
  - 7.95103
  14:
  - -1.664776
  - 0.503269
  15:
  - -0.231688
  - 1.997731
  16:
  - 4.799464
  - 6.310804
  17:
  - 4.828616
  - 7.662571
